prefix = '_cms-mk_'
title = 'MK CMS'
supportedLocales = ['en-us', 'vi-vn']
timezone = 'Asia/Ho_Chi_Minh'
modules = ['core', 'user', 'song', 'youtube', 'dashboard', 'dhamma', 'news']

[idv3]
mutagenInspect = '/usr/local/bin/mutagen-inspect'
mid3v2 = '/usr/local/bin/mid3v2'

[cache]
lifetime = 86400
adapter = 'Libmemcached'
[cache.client]
\Memcached::OPT_HASH = '\Memcached::HASH_MD5'
\Memcached::OPT_PREFIX_KEY = '_cms-olli_.'

[logger]
path = '/app/storage/logs/'
format = '[%datetime%] [%channel%] [%level_name%] %message% %context%\n'

# Only using in production
[annotations]
annotationsDir = '/app/storage/cache/annotations/'

# Only using in production
[metadata]
metaDataDir = '/app/storage/cache/metadata/'

[users]
directory = '/app/storage/files/users/'
minsize = 100
maxsize = 10000000
mimes = ['image/jpeg', 'image/jpg', 'image/png']
isoverwrite = false
thumbsize = '300x200'
mediumsize = '540x100'
fullsize = '1200x1200'

[songs]
directory = '/app/storage/files/songs/'
minsize = 100
maxsize = 1024000000
mimes = ['audio/mpeg', 'audio/mp3']
isoverwrite = false

[dhammas]
directory = '/app/storage/files/dhammas/'
minsize = 100
maxsize = 1024000000
mimes = ['audio/mpeg', 'audio/mp3']
isoverwrite = false
